#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat May  1 15:42:16 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1000, 493))
        self.SetTitle("Mapomatic")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Start Location")
        sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.TOP, 10)

        self.text_ctrl_ = wx.SearchCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_.ShowCancelButton(True)
        sizer_2.Add(self.text_ctrl_, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "End location\n")
        sizer_2.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.text_ctrl_2 = wx.SearchCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_2.ShowCancelButton(True)
        sizer_2.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        self.checkbox_1 = wx.CheckBox(self.panel_1, wx.ID_ANY, "Wheel Chair Access")
        sizer_2.Add(self.checkbox_1, 0, 0, 0)

        self.button_Submit = wx.Button(self.panel_1, wx.ID_ANY, "Submit")
        sizer_2.Add(self.button_Submit, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        self.panel_2.SetMinSize((1000, 400))
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_SEARCHCTRL_CANCEL_BTN, self.asd, self.text_ctrl_)
        self.Bind(wx.EVT_SEARCHCTRL_SEARCH_BTN, self.fdd, self.text_ctrl_)
        self.Bind(wx.EVT_TEXT, self.text_f, self.text_ctrl_)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_eventtt, self.text_ctrl_)
        self.Bind(wx.EVT_CHECKBOX, self.on_checked, self.checkbox_1)
        # end wxGlade

    def asd(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'asd' not implemented!")
        event.Skip()

    def fdd(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'fdd' not implemented!")
        event.Skip()

    def text_f(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'text_f' not implemented!")
        event.Skip()

    def on_eventtt(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_eventtt' not implemented!")
        event.Skip()

    def on_checked(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_checked' not implemented!")
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
