#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Tue Apr 27 15:34:59 2021
#

import wx
import gmplot
from cefpython3 import cefpython as cef
import sys
import platform
import os
from wx.core import HORIZONTAL

WINDOWS = (platform.system() == "Windows")
LINUX = (platform.system() == "Linux")
MAC = (platform.system() == "Darwin")


WIDTH = 900
HEIGHT = 640


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
apikey = 'AIzaSyDNhX6JLoc3uTlVV30AhkIZ_wFDoqnYYUI' # (your API key here)

def main():
    check_versions()
    sys.excepthook = cef.ExceptHook  # To shutdown all CEF processes on error
    settings = {}
    cef.DpiAware.EnableHighDpiSupport()
    cef.Initialize(settings=settings)
    app = CefApp(False)
    app.MainLoop()
    del app  # Must destroy before calling Shutdown

    cef.Shutdown()


def check_versions():
    print("[wxpython.py] CEF Python {ver}".format(ver=cef.__version__))
    print("[wxpython.py] Python {ver} {arch}".format(
            ver=platform.python_version(), arch=platform.architecture()[0]))
    print("[wxpython.py] wxPython {ver}".format(ver=wx.version()))
    # CEF Python version requirement
    assert cef.__version__ >= "66.0", "CEF Python v66.0+ required to run this"


def scale_window_size_for_high_dpi(width, height):
    """Scale window size for high DPI devices. This func can be
    called on all operating systems, but scales only for Windows.
    If scaled value is bigger than the work area on the display
    then it will be reduced."""
    if not WINDOWS:
        return width, height
    (_, _, max_width, max_height) = wx.GetClientDisplayRect().Get()
    # noinspection PyUnresolvedReferences
    (width, height) = cef.DpiAware.Scale((width, height))
    if width > max_width:
        width = max_width
    if height > max_height:
        height = max_height
    return width, height

class MainFrame(wx.Frame):
    def __init__(self):
        self.browser = None
        # begin wxGlade: MyFrame.__init__

        
        if WINDOWS:
            # noinspection PyUnresolvedReferences, PyArgumentList
            print("[wxpython.py] System DPI settings: %s"
                  % str(cef.DpiAware.GetSystemDpi()))
        if hasattr(wx, "GetDisplayPPI"):
            print("[wxpython.py] wx.GetDisplayPPI = %s" % wx.GetDisplayPPI())
        print("[wxpython.py] wx.GetDisplaySize = %s" % wx.GetDisplaySize())

        print("[wxpython.py] MainFrame declared size: %s"
              % str((WIDTH, HEIGHT)))
        size = scale_window_size_for_high_dpi(WIDTH, HEIGHT)
        print("[wxpython.py] MainFrame DPI scaled size: %s" % str(size))
        




        wx.Frame.__init__(self,parent=None, id=wx.ID_ANY,title='wxPython example', size=size)
        print("[wxpython.py] MainFrame actual size: %s" % self.GetSize())
        self.Bind(wx.EVT_CLOSE, self.OnClose)

        self.SetSize((1000, 500))
        self.SetTitle("Mapomatic")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.text_ctrl_search = wx.SearchCtrl(self.panel_1, wx.ID_ANY, "Nigh Center")
        self.text_ctrl_search.ShowCancelButton(True)
        sizer_2.Add(self.text_ctrl_search, 0, wx.ALL | wx.EXPAND, 2)

        self.radio_btn_WCA = wx.RadioButton(self.panel_1, wx.ID_ANY, "Wheel Chair Access")
        sizer_2.Add(self.radio_btn_WCA, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 1)

        self.button_Submit = wx.Button(self.panel_1, wx.ID_ANY, "Submit")
        sizer_2.Add(self.button_Submit, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        
        # self.browser_panel = wx.Panel(self)
        # self.browser_panel.Bind(wx.EVT_SET_FOCUS, self.OnSetFocus)
        # self.browser_panel.Bind(wx.EVT_SIZE, self.OnSize)
         
        # self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        # self.panel_2.SetMinSize((1000, 400))
        self.browser_panel = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        self.browser_panel.SetMinSize((1000, 400))
        self.browser_panel.Bind(wx.EVT_SET_FOCUS, self.OnSetFocus)
        self.browser_panel.Bind(wx.EVT_SIZE, self.OnSize)
         
        # self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        # self.panel_2.SetMinSize((1000, 400))
        sizer_1.Add(self.browser_panel, 1, wx.EXPAND, 0)

        
        # sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        # sizer_3.Add(self.browser_panel)
        # sizer_3.Add((0, 0), 0, 0, 0)

        # self.panel_2.SetSizer(sizer_3)
        self.panel_1.SetSizer(sizer_1)

        

        
        self.embed_browser()
        self.Show()
        self.Layout()
        # end wxGlade
    
    def embed_browser(self):
        gmap = gmplot.GoogleMapPlotter.from_geocode('Chiyoda City, Tokyo', apikey=apikey)
        gmap.draw("map.html")
        window_info = cef.WindowInfo()
        (width, height) = self.browser_panel.GetClientSize().Get()
        assert self.browser_panel.GetHandle(), "Window handle not available"
        window_info.SetAsChild(self.browser_panel.GetHandle(),
                               [0, 0, width, height])
        self.browser = cef.CreateBrowserSync(window_info,
                                             url="file:///C:/Users/ninte/Documents/School/Software%20I/Project/map.html")
        self.browser.SetClientHandler(FocusHandler())
    def OnSetFocus(self, _):
        
        cef.WindowUtils.OnSetFocus(self.browser_panel.GetHandle(),
                                       0, 0, 0)
        self.browser.SetFocus(True)
     

    def OnSize(self, _):
        cef.WindowUtils.OnSize(self.browser_panel.GetHandle(),
                                   0, 0, 0)
    
        self.browser.NotifyMoveOrResizeStarted()

    def OnClose(self, event):
        print("[wxpython.py] OnClose called")
        
        self.browser.ParentWindowWillClose()
        event.Skip()
        self.clear_browser_references()



    def OnClose(self, event):
        print("[wxpython.py] OnClose called")
        if not self.browser:
            # May already be closing, may be called multiple times on Mac
            return
        self.browser.ParentWindowWillClose()
        event.Skip()
        self.clear_browser_references()
    def clear_browser_references(self):
        # Clear browser references that you keep anywhere in your
        # code. All references must be cleared for CEF to shutdown cleanly.
        self.browser = None

# end of class MyFrame
class FocusHandler(object):
    def OnGotFocus(self, browser, **_):
        # Temporary fix for focus issues on Linux (Issue #284).
        if LINUX:
            print("[wxpython.py] FocusHandler.OnGotFocus:"
                  " keyboard focus fix (Issue #284)")
            browser.SetFocus(True)
class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True
class CefApp(wx.App):

    def __init__(self, redirect):
        self.timer = None
        self.timer_id = 1
        self.is_initialized = False
        super(CefApp, self).__init__(redirect=redirect)

    def OnPreInit(self):
        super(CefApp, self).OnPreInit()
        # On Mac with wxPython 4.0 the OnInit() event never gets
        # called. Doing wx window creation in OnPreInit() seems to
        # resolve the problem (Issue #350).
        if MAC and wx.version().startswith("4."):
            print("[wxpython.py] OnPreInit: initialize here"
                  " (wxPython 4.0 fix)")
            self.initialize()

    def OnInit(self):
        self.initialize()
        return True

    def initialize(self):
        if self.is_initialized:
            return
        self.is_initialized = True
        self.create_timer()
        frame = MainFrame()
        self.SetTopWindow(frame)
        frame.Show()

    def create_timer(self):
        # See also "Making a render loop":
        # http://wiki.wxwidgets.org/Making_a_render_loop
        # Another way would be to use EVT_IDLE in MainFrame.
        self.timer = wx.Timer(self, self.timer_id)
        self.Bind(wx.EVT_TIMER, self.on_timer, self.timer)
        self.timer.Start(10)  # 10ms timer

    def on_timer(self, _):
        cef.MessageLoopWork()

    def OnExit(self):
        self.timer.Stop()
        return 0
# end of class MyApp

if __name__ == "__main__":
    main()

